name: communis
version: '${version}'
main: the.grid.smp.communis.Communis
api-version: '1.18'
libraries:
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.16.0
  - com.fasterxml.jackson.core:jackson-annotations:2.16.0
